export const peliculas = [
    {
        id: 1,
        titulo: "DESTINO FINAL LAZOS DE SANGRE",
        imagen: "image/cartelera/destino-final.jpg",
        clasificacion: "+16",
        formato: "2D · 4D E-MOTION · D-BOX · PREMIUM CLASS · XD DIGITAL · COMFORT",
        destacado: true,
        duracion: "1h 50m",
        estreno: true,
        reestreno: false,
        preventa: true,
        alternativo: true,
    },
    {
        id: 2,
        titulo: "THUNDERBOLTS",
        imagen: "image/cartelera/thunderbolts.jpg",
        clasificacion: "+13",
        formato: "3D · 4D E-MOTION · COMFORT · D-BOX · 2D · PREMIUM CLASS",
        destacado: true,
        duracion: "2h 16m",
        estreno: false,
        reestreno: false,
        preventa: true,
        alternativo: false,
    },
    {
        id: 3,
        titulo: "KARATE KID LEYENDAS",
        imagen: "image/cartelera/karate-kid.jpg",
        clasificacion: "+13",
        formato: "2D",
        destacado: true,
        duracion: "1h 33m",
        estreno: false,
        reestreno: false,
        preventa: true,
        alternativo: false,
    },
    {
        id: 4,
        titulo: "UNA PELICULA DE MINECRAFT",
        imagen: "image/cartelera/minecraft.jpg",
        clasificacion: "ATP",
        formato: "3D · 2D",
        destacado: true,
        duracion: "1h 41m",
        estreno: false,
        reestreno: false,
        preventa: true,
        alternativo: false,
    },
    {
        id: 5,
        titulo: "MAZEL TOV",
        imagen: "image/cartelera/mazel-tov.jpg",
        clasificacion: "+13",
        formato: "2D · PREMIUM CLASS",
        destacado: true,
        duracion: "1h 37m",
        estreno: false,
        reestreno: false,
        preventa: true,
        alternativo: false,
    },
    {
        id: 6,
        titulo: "COLORFUL STAGE! MIKU NO PUEDE CANTAR",
        imagen: "image/cartelera/miku.jpg",
        clasificacion: "ATP",
        formato: "2D",
        destacado: false,
        duracion: "1h 45m",
        estreno: true,
        reestreno: false,
        preventa: false,
        alternativo: false,
    },
    {
        id: 7,
        titulo: "LA LEYENDA DE OCHI",
        imagen: "image/cartelera/leyenda-ochi.jpg",
        clasificacion: "ATP",
        formato: "2D",
        destacado: false,
        duracion: "1h 24m",
        estreno: true,
        reestreno: false,
        preventa: false,
        alternativo: false,
    },
    {
        id: 8,
        titulo: "GLORIA",
        imagen: "image/cartelera/gloria.jpg",
        clasificacion: "+13",
        formato: "2D",
        destacado: false,
        duracion: "1h 46m",
        estreno: true,
        reestreno: false,
        preventa: false,
        alternativo: false,
    },
    {
        id: 9,
        titulo: "EL ROBO DEL SIGLO (2020)",
        imagen: "image/cartelera/robo-siglo.jpg",
        clasificacion: "+13",
        formato: "2D",
        destacado: false,
        duracion: "1h 54m",
        estreno: true,
        reestreno: true,
        preventa: false,
        alternativo: false,
    },
    {
        id: 10,
        titulo: "ESPERANDO LA CARROZA (1985)",
        imagen: "image/cartelera/esperando-carroza.jpg",
        clasificacion: "ATP",
        formato: "2D",
        destacado: false,
        duracion: "1h 34m",
        reestreno: false,
        preventa: false,
        alternativo: false,
    },
    {
        id: 11,
        titulo: "ENCERRADO",
        imagen: "image/cartelera/encerrado.jpg",
        clasificacion: "+16",
        formato: "2D",
        destacado: false,
        duracion: "1h 35m",
        reestreno: false,
        preventa: false,
        alternativo: false,
    },
    {
        id: 12,
        titulo: "UNTIL DAWN NOCHE DE TERROR",
        imagen: "image/cartelera/until-dawn.jpg",
        clasificacion: "+16",
        formato: "2D",
        destacado: false,
        duracion: "1h 43m",
        reestreno: false,
        preventa: false,
        alternativo: false,
    },
    {
        id: 13,
        titulo: "EL CONTADOR 2",
        imagen: "image/cartelera/contador.jpg",
        clasificacion: "+16",
        formato: "2D",
        destacado: false,
        duracion: "2h 12m",
        reestreno: false,
        preventa: false,
        alternativo: false,
    },
    {
        id: 14,
        titulo: "PECADORES",
        imagen: "image/cartelera/pecadores.jpg",
        clasificacion: "+13",
        formato: "2D",
        destacado: false,
        duracion: "2h 18m",
        reestreno: false,
        preventa: false,
        alternativo: false,
    },
    {
        id: 15,
        titulo: "BLANCA NIEVES",
        imagen: "image/cartelera/blanca-nieves.jpg",
        clasificacion: "ATP",
        formato: "2D",
        destacado: false,
        duracion: "1h 46m",
        reestreno: false,
        preventa: false,
        alternativo: true,
    }
];

