export const peliculas = [
  {
    id: 1,
    titulo: "DESTINO FINAL LAZOS DE SANGRE",
    imagen: "image/cartelera/destino-final.jpg",
    clasificacion: "+16",
    formato: "2D · 4D E-MOTION · D-BOX · PREMIUM CLASS · XD DIGITAL · COMFORT",
    destacado: true,
    duracion: "1h 50m",
    estreno: true,
    reestreno: false,
    cartelera: true,
    preventa: false,
    alternativo: false,
    proximoEstreno: false,
  },
  {
    id: 2,
    titulo: "THUNDERBOLTS",
    imagen: "image/cartelera/thunderbolts.jpg",
    clasificacion: "+13",
    formato: "3D · 4D E-MOTION · COMFORT · D-BOX · 2D · PREMIUM CLASS",
    destacado: true,
    duracion: "2h 16m",
    estreno: false,
    reestreno: false,
    cartelera: true,
    preventa: false,
    alternativo: false,
    proximoEstreno: false,
  },
  {
    id: 3,
    titulo: "KARATE KID LEYENDAS",
    imagen: "image/cartelera/karate-kid.jpg",
    clasificacion: "+13",
    formato: "2D",
    destacado: true,
    duracion: "1h 33m",
    estreno: false,
    reestreno: false,
    cartelera: true,
    preventa: false,
    alternativo: false,
    proximoEstreno: false,
  },
  {
    id: 4,
    titulo: "UNA PELICULA DE MINECRAFT",
    imagen: "image/cartelera/minecraft.jpg",
    clasificacion: "ATP",
    formato: "3D · 2D",
    destacado: true,
    duracion: "1h 41m",
    estreno: false,
    reestreno: false,
    cartelera: true,
    preventa: false,
    alternativo: false,
    proximoEstreno: false,
  },
  {
    id: 5,
    titulo: "MAZEL TOV",
    imagen: "image/cartelera/mazel-tov.jpg",
    clasificacion: "+13",
    formato: "2D · PREMIUM CLASS",
    destacado: true,
    duracion: "1h 37m",
    estreno: false,
    reestreno: false,
    cartelera: true,
    preventa: false,
    alternativo: false,
    proximoEstreno: false,
  },
  {
    id: 6,
    titulo: "COLORFUL STAGE! MIKU NO PUEDE CANTAR",
    imagen: "image/cartelera/miku.jpg",
    clasificacion: "ATP",
    formato: "2D",
    destacado: false,
    duracion: "1h 45m",
    estreno: true,
    reestreno: false,
    cartelera: true,
    preventa: false,
    alternativo: false,
    proximoEstreno: false,
  },
  {
    id: 7,
    titulo: "LA LEYENDA DE OCHI",
    imagen: "image/cartelera/leyenda-ochi.jpg",
    clasificacion: "ATP",
    formato: "2D",
    destacado: false,
    duracion: "1h 24m",
    estreno: true,
    reestreno: false,
    cartelera: true,
    preventa: false,
    alternativo: false,
    proximoEstreno: false,
  },
  {
    id: 8,
    titulo: "GLORIA",
    imagen: "image/cartelera/gloria.jpg",
    clasificacion: "+13",
    formato: "2D",
    destacado: false,
    duracion: "1h 46m",
    estreno: true,
    reestreno: false,
    cartelera: true,
    preventa: false,
    alternativo: false,
    proximoEstreno: false,
  },
  {
    id: 9,
    titulo: "EL ROBO DEL SIGLO (2020)",
    imagen: "image/cartelera/robo-siglo.jpg",
    clasificacion: "+13",
    formato: "2D",
    destacado: false,
    duracion: "1h 54m",
    estreno: true,
    reestreno: true,
    cartelera: true,
    preventa: false,
    alternativo: false,
    proximoEstreno: false,
  },
  {
    id: 10,
    titulo: "ESPERANDO LA CARROZA (1985)",
    imagen: "image/cartelera/esperando-carroza.jpg",
    clasificacion: "ATP",
    formato: "2D",
    destacado: false,
    duracion: "1h 34m",
    estreno: false,
    reestreno: false,
    cartelera: true,
    preventa: false,
    alternativo: false,
    proximoEstreno: false,
  },
  {
    id: 11,
    titulo: "ENCERRADO",
    imagen: "image/cartelera/encerrado.jpg",
    clasificacion: "+16",
    formato: "2D",
    destacado: false,
    duracion: "1h 35m",
    estreno: false,
    reestreno: false,
    cartelera: true,
    preventa: false,
    alternativo: false,
    proximoEstreno: false,
  },
  {
    id: 12,
    titulo: "UNTIL DAWN NOCHE DE TERROR",
    imagen: "image/cartelera/until-dawn.jpg",
    clasificacion: "+16",
    formato: "2D",
    destacado: false,
    duracion: "1h 43m",
    estreno: false,
    reestreno: false,
    cartelera: true,
    preventa: false,
    alternativo: false,
    proximoEstreno: false,
  },
  {
    id: 13,
    titulo: "EL CONTADOR 2",
    imagen: "image/cartelera/contador.jpg",
    clasificacion: "+16",
    formato: "2D",
    destacado: false,
    duracion: "2h 12m",
    estreno: false,
    reestreno: false,
    cartelera: true,
    preventa: false,
    alternativo: false,
    proximoEstreno: false,
  },
  {
    id: 14,
    titulo: "PECADORES",
    imagen: "image/cartelera/pecadores.jpg",
    clasificacion: "+13",
    formato: "2D",
    destacado: false,
    duracion: "2h 18m",
    estreno: false,
    reestreno: false,
    cartelera: true,
    preventa: false,
    alternativo: false,
    proximoEstreno: false,
  },
  {
    id: 15,
    titulo: "BLANCA NIEVES",
    imagen: "image/cartelera/blanca-nieves.jpg",
    clasificacion: "ATP",
    formato: "2D",
    destacado: false,
    duracion: "1h 46m",
    estreno: false,
    reestreno: false,
    cartelera: true,
    preventa: false,
    alternativo: true,
    proximoEstreno: false,
  },
  {
    id: 16,
    titulo: "MISION IMPOSIBLE LA SENTENCIA MORTAL",
    imagen: "image/peliculas-preventa/mision-imposible.jpg",
    clasificacion: "+13",
    formato: "2D · 4D E-MOTION · D-BOX · PREMIUM CLASS · XD DIGITAL · COMFORT",
    destacado: false,
    duracion: "2h 49m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: true,
    alternativo: false,
    proximoEstreno: false,
  },
  {
    id: 17,
    titulo: "LILO Y STITCH",
    imagen: "image/peliculas-preventa/stitch.jpg",
    clasificacion: "ATP",
    formato:
      "3D · 4D E-MOTION · D-BOX · 2D · COMFORT · PREMIUM CLASS · XD DIGITAL",
    destacado: false,
    duracion: "1h 48m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: true,
    alternativo: false,
    proximoEstreno: false,
  },
  {
    id: 18,
    titulo: "J-HOP TOUR JAPAN LIVE VIEWING",
    imagen: "image/peliculas-preventa/j-hop.jpg",
    clasificacion: "ATP",
    formato: "2D",
    destacado: false,
    duracion: "3h",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: true,
    alternativo: true,
    proximoEstreno: false,
  },
  {
    id: 19,
    titulo: "ADO SPECIAL LIVE SHINZOU IN CINEMA",
    imagen: "image/peliculas-preventa/ado.jpg",
    clasificacion: "ATP",
    formato: "2D",
    destacado: false,
    duracion: "2h 20m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: true,
    alternativo: false,
    proximoEstreno: false,
  },
  {
    id: 20,
    titulo: "BAILARINA",
    imagen: "image/peliculas-preventa/bailarina.jpg",
    clasificacion: "+16",
    formato: "2D · D-BOX · PREMIUM CLASS · XD DIGITAL · COMFORT",
    destacado: false,
    duracion: "2h 5m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: true,
    alternativo: false,
    proximoEstreno: false,
  },
  {
    id: 21,
    titulo: "FUERA DE TEMPORADA",
    imagen: "image/proximos-estrenos/fuera-temporada.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "1h 55m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "12/06/2025",
  },
  {
    id: 22,
    titulo: "HECHO MIERD@",
    imagen: "image/proximos-estrenos/hecho-mierda.jpg",
    clasificacion: "+16",
    formato: null,
    destacado: false,
    duracion: "1h 30m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "12/06/2025",
  },
  {
    id: 23,
    titulo: "KABADDI",
    imagen: "image/proximos-estrenos/kabaddi.jpg",
    clasificacion: "+13",
    formato: null,
    destacado: false,
    duracion: "2h 9m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "19/06/2025",
  },
  {
    id: 24,
    titulo: "ELIO",
    imagen: "image/proximos-estrenos/elio.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "1h 40m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "19/06/2025",
  },
  {
    id: 25,
    titulo: "EXTERMINIO LA EVOLUCION",
    imagen: "image/proximos-estrenos/exterminio.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "1h 55m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "19/06/2025",
  },
  {
    id: 26,
    titulo: "LA VENGANZA",
    imagen: "image/proximos-estrenos/venganza.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "1h 40m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "26/06/2025",
  },
  {
    id: 27,
    titulo: "MEGAN 2.0",
    imagen: "image/proximos-estrenos/megan.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "1h 40m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "26/06/2025",
  },
  {
    id: 28,
    titulo: "JURASSIC WORLD RENACE",
    imagen: "image/proximos-estrenos/jurassic.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "2h 14m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "03/07/2025",
  },
  {
    id: 29,
    titulo: "SUPERMAN",
    imagen: "image/proximos-estrenos/superman.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "2h 9m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "10/07/2025",
  },
  {
    id: 30,
    titulo: "EL NOVIO DE MAMÁ",
    imagen: "image/proximos-estrenos/el-novio.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "1h 30m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "17/07/2025",
  },
  {
    id: 31,
    titulo: "SE LO QUE HICIERON EL VERANO PASADO",
    imagen: "image/proximos-estrenos/verano-pasado.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "1h 30m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "17/07/2025",
  },
  {
    id: 32,
    titulo: "PITUFOS",
    imagen: "image/proximos-estrenos/pitufos.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "1h 30m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "17/07/2025",
  },
  {
    id: 33,
    titulo: "LOS 4 FANTASTICOS: PRIMEROS PASOS",
    imagen: "image/proximos-estrenos/fantasticos.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "1h 30m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "24/07/2025",
  },
  {
    id: 34,
    titulo: "AMORES MATERIALISTAS",
    imagen: "image/proximos-estrenos/materialistas.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "1h 30m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "31/07/2025",
  },
  {
    id: 35,
    titulo: "EXORCISMO EL RITUAL",
    imagen: "image/proximos-estrenos/exorcismo.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "1h 30m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "31/07/2025",
  },
  {
    id: 36,
    titulo: "¿Y DONDE ESTA EL POLICIA?",
    imagen: "image/proximos-estrenos/donde-esta.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "1h 30m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "31/07/2025",
  },
  {
    id: 37,
    titulo: "LOS TIPOS MALOS 2",
    imagen: "image/proximos-estrenos/tipos-malos.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "1h 30m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "31/07/2025",
  },
  {
    id: 38,
    titulo: "LA HORA DE LA DESAPARICION",
    imagen: "image/proximos-estrenos/hora-desaparicion.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "2h 8m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "07/08/2025",
  },
  {
    id: 39,
    titulo: "OTRO VIERNES DE LOCOS",
    imagen: "image/proximos-estrenos/viernes-locos.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "1h 30m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "07/08/2025",
  },
  {
    id: 40,
    titulo: "HOMO ARGENTUM",
    imagen: "image/proximos-estrenos/argentum.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "2h",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "14/08/2025",
  },
  {
    id: 41,
    titulo: "NADIE 2",
    imagen: "image/proximos-estrenos/nadie.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "1h 30m",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "21/08/2025",
  },
  {
    id: 42,
    titulo: "HAZ QUE REGRESE",
    imagen: "image/proximos-estrenos/que-regrese.jpg",
    clasificacion: "ATP",
    formato: null,
    destacado: false,
    duracion: "2h",
    estreno: false,
    reestreno: false,
    cartelera: false,
    preventa: false,
    alternativo: false,
    proximoEstreno: true,
    fecha: "21/08/2025",
  },
];
